// This file was generated by liblab | https://liblab.com/

import Toolhouse from '@toolhouseai/toolhouse-sdk-typescript';

(async () => {
  const toolhouse = new Toolhouse({
    token: '0cbecd64-cc45-45c7-829c-a56db6881de1',
  });

  const { data } = await toolhouse.tools.toolsToolsGet();

  console.log(data);
})();
