// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const inputSchemaType = z.literal('object')

export type InputSchemaType = z.infer<typeof inputSchemaType>;
