// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const openAiToolRequestType = z.literal('function')

export type OpenAiToolRequestType = z.infer<typeof openAiToolRequestType>;
