// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const toolhouseApiModelsProvidersProvidersToolsOpenaiToolType = z.literal('function');

export type ToolhouseApiModelsProvidersProvidersToolsOpenaiToolType = z.infer<
  typeof toolhouseApiModelsProvidersProvidersToolsOpenaiToolType
>;
