// This file was generated by liblab | https://liblab.com/

import { Environment } from './http/environment';
import { SdkConfig } from './http/types';
import { ToolsService } from './services/tools';

export * from './services/tools';

export type * from './http';

export default class Toolhouse {
  public readonly tools: ToolsService;

  constructor(public config: SdkConfig) {
    const baseUrl = config.environment || config.baseUrl || Environment.DEFAULT;
    this.config = {
      ...config,
      baseUrl,
    };
    this.tools = new ToolsService(this.config);
  }

  set baseUrl(baseUrl: string) {
    this.tools.baseUrl = baseUrl;
  }

  set environment(environment: Environment) {
    this.tools.baseUrl = environment;
  }

  set timeoutMs(timeoutMs: number) {
    this.tools.timeoutMs = timeoutMs;
  }

  set token(token: string) {
    this.tools.token = token;
  }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
